apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-main
  namespace: monitoring
type: Opaque
stringData:
  alertmanager.yaml: |
    global:
      resolve_timeout: 5m
      smtp_from: blackvins9@gmail.com
      smtp_smarthost: smtp.gmail.com:587
      smtp_auth_username: blackvins9@gmail.com
      smtp_auth_password: oiissqzssxlxqibk  # Utilisez un mot de passe d'application
      smtp_require_tls: true

    route:
      group_by: ['alertname']
      group_wait: 10s
      group_interval: 5m
      repeat_interval: 3h
      receiver: 'gmail-notifications'

    receivers:
    - name: 'gmail-notifications'
      email_configs:
      - to: blackvins9@gmail.com
        send_resolved: true  # Notification quand l'alerte est résolue
        html: '{{ template "email.default.html" . }}'

    templates:
    - '/etc/alertmanager/template/*.tmpl'
