# alert-rules.yaml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: crashloop-alerts
  namespace: monitoring
spec:
  groups:
  - name: autoheal.rules
    rules:
    - alert: PodCrashLooping
      expr: kube_pod_container_status_waiting_reason{reason="CrashLoopBackOff"} == 1
      for: 1m
      labels:
        severity: critical
        autoheal: "true"
      annotations:
        summary: "Pod {{ $labels.pod }} en CrashLoopBackOff"
        description: "Déclenchement de l'auto-réparation via ArgoCD"
