apiVersion: batch/v1
kind: Job
metadata:
  name: restart-pods
spec:
  template:
    spec:
      containers:
      - name: restart
        image: bitnami/kubectl:latest
        command: ["kubectl", "delete", "pod", "-l", "app=tfc-app"]
      restartPolicy: Never
